version: 366.0.1.4
clone_depth: 5
image: Visual Studio 2019

only_commits:
  message: /build/

build_script:
- '"C:\Program Files (x86)\NSIS\makensis.exe" uotiara.nsi'

artifacts:
- path: '*.exe'
  name: uotiara