version: 383.0.16.35
clone_depth: 5
skip_tags: true
image: Visual Studio 2017

build_script:
- '"C:\Program Files (x86)\NSIS\makensis.exe" uotiara.nsi'

artifacts:
- path: '*.exe'
  name: uotiara
- path: 'data_99999.it'
  name: uotiara

deploy:
- provider: Environment
  name: uotiara