version: 381.0.14.33
clone_depth: 5
skip_tags: true
image: Visual Studio 2017

build_script:
- '"C:\Program Files (x86)\NSIS\makensis.exe" uotiara.nsi'

artifacts:
- path: '*.exe'
  name: uotiara
- path: 'UOTiara.pack'
  name: uotiara
- path: 'language.pack'
  name: uotiara

deploy:
- provider: Environment
  name: uotiara